package bs.protocol;

import bs.logging.ProgramException;

public class VersionMismatchException extends ProgramException
{
	private static final long serialVersionUID = 4980325701019738580L;

	public VersionMismatchException(final String actualVersion, final String expectedVersion)
	{
		super(String.format("message was generated by a different version (%s) of this service, you are running version %s!", expectedVersion, actualVersion));
	}
}