package bs;

public class VersionMismatchException extends Exception
{
	private static final long serialVersionUID = 4980325701019738580L;

	public VersionMismatchException(final String actualVersion,final String expectedVersion)
	{
		m_message = String.format(
			"message was generated by a different version (%s) of this service, you are running version %s!",
			expectedVersion, actualVersion);
	}

	private final String m_message;

	@Override
	public String getMessage()
	{
		return m_message;
	}
}